Add a Bug
RECOMGmbH/RecomTest pull request #1
Opened 2020-02-26 07:40 UTC by sys0r2

Please fix the Bug

2020-02-26 08:00 UTC, tobster-de commented on HelloWorld/UnitTestProject/ViewModelTest.cs
> +            BUG !!
offensichtlich ein Fehler

2020-02-26 10:16 UTC, kseidl commented on HelloWorld/UnitTestProject/ViewModelTest.cs
> +            BUG !!
I think, this will prob. not compile

2020-02-26 10:18 UTC, kseidl commented on HelloWorld/UnitTestProject/ViewModelTest.cs
> +            BUG !!
Test->Web to VS message sync

2020-02-26 10:21 UTC, kseidl commented on HelloWorld/UnitTestProject/ViewModelTest.cs
> +            BUG !!
Next Test

2020-07-16 07:44 UTC, tkolb-recom requested changes

2020-07-16 07:44 UTC, tgaertner-recom commented on HelloWorld/UnitTestProject/ViewModelTest.cs
> +            BUG !! // Test review
Please fix BUG

2020-10-30 18:36 UTC, closed without merging